plugins:
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss
singleQuote: true
trailingComma: all
printWidth: 100
tabWidth: 2
bracketSpacing: true
endOfLine: lf
overrides:
  - files: '*.{js,jsx,ts,tsx}'
    options:
      parser: typescript
  - files: '*.astro'
    options:
      parser: astro
